=== open-dis/viskit/Schemas/assembly.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com) by Don Brutzman (Naval Postgraduate School) -->
<!-- SVN ID: $Id$ -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:group name="DesignParameters">
		<xs:sequence>
			<xs:element ref="TerminalParameter"/>
		</xs:sequence>
	</xs:group>
	<xs:element name="ValueRange" abstract="true">
		<xs:complexType>
			<xs:attribute name="lowValue"/>
			<xs:attribute name="highValue"/>
		</xs:complexType>
	</xs:element>
	<xs:group name="Parameters">
		<xs:choice>
			<xs:element ref="MultiParameter"/>
			<xs:element ref="FactoryParameter"/>
			<xs:element ref="TerminalParameter"/>
		</xs:choice>
	</xs:group>
	<xs:element name="Statistics" abstract="true"/>
	<xs:element name="SimkitAssembly">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="head" minOccurs="0"/>
				<xs:group ref="DesignParameters" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="SimEntity" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="EventGraph" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="PropertyChangeListener" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="SimEventListenerConnection" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="PropertyChangeListenerConnection" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Adapter" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Output" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Verbose" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Schedule" minOccurs="0"/>
				<xs:element ref="Experiment" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:ID" use="required"/>
			<xs:attribute name="created"/>
			<xs:attribute name="version"/>
			<xs:attribute name="package" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="author"/>
			<xs:attribute name="extend" default="viskit.assembly.ViskitAssembly"/>
			<xs:attribute name="implement"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="head">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="meta" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="meta">
		<xs:complexType>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="content"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="SimEntity">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="Parameters" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Coordinate" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="type" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="url"/>
			<xs:attribute name="description"/>
			<xs:attribute name="verbose" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="TerminalParameter">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ValueRange" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string"/>
			<xs:attribute name="linkRef" type="xs:IDREF"/>
			<xs:attribute name="link" type="xs:ID"/>
			<xs:attribute name="value"/>
			<xs:attribute name="type" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="description"/>
			<!-- name may be contained in parent element FactoryParameter, thus xs:string and not required -->
		</xs:complexType>
	</xs:element>
	<xs:element name="DoubleRange" substitutionGroup="ValueRange"/>
	<xs:element name="IntegerRange" substitutionGroup="ValueRange"/>
	<xs:element name="MultiParameter">
		<xs:complexType>
			<xs:group ref="Parameters" minOccurs="0" maxOccurs="unbounded"/>
			<xs:attribute name="name" type="xs:NMTOKEN"/>
			<xs:attribute name="type" type="xs:string" use="required"/>
			<xs:attribute name="description"/>
			<!-- xs:NMTOKEN not feasible due to array types, e.g. int[] -->
		</xs:complexType>
	</xs:element>
	<xs:element name="FactoryParameter">
		<xs:complexType>
			<xs:group ref="Parameters" minOccurs="0" maxOccurs="unbounded"/>
			<xs:attribute name="name" type="xs:NMTOKEN"/>
			<xs:attribute name="factory" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="method" type="xs:NMTOKEN" default="getInstance"/>
			<xs:attribute name="type" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Coordinate">
		<xs:complexType>
			<xs:attribute name="x" use="required"/>
			<xs:attribute name="y" use="required"/>
			<!-- TODO  type="xs:float" -->
			<!-- TODO  type="xs:float" -->
		</xs:complexType>
	</xs:element>
	<!--
     The proper mode for a PropertyChangeListener is singular, however, for
    backwards compatibility with older EventGraphs, we allow both singular and
    plural modes (tdn 16 SEP 2008)
  -->
	<xs:element name="PropertyChangeListener">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="Parameters" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Coordinate" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:ID" use="required"/>
			<xs:attribute name="type" use="required"/>
			<xs:attribute name="mode" default="listener">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="replicationStat"/>
						<xs:enumeration value="replicationStats"/>
						<xs:enumeration value="designPointStat"/>
						<xs:enumeration value="designPointStats"/>
						<xs:enumeration value="listener"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="meanStatistics" default="false">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="true"/>
						<xs:enumeration value="false"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="countStatistics" default="true">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="true"/>
						<xs:enumeration value="false"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="SimEventListenerConnection">
		<xs:complexType>
			<xs:attribute name="listener" use="required"/>
			<xs:attribute name="source" use="required"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="PropertyChangeListenerConnection">
		<xs:complexType>
			<xs:attribute name="property"/>
			<xs:attribute name="listener" use="required"/>
			<xs:attribute name="source" use="required"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Output">
		<xs:complexType>
			<xs:attribute name="entity" type="xs:NMTOKEN" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Verbose">
		<xs:complexType>
			<xs:attribute name="entity" type="xs:NMTOKEN" use="required"/>
			<!-- Bugfix 1425 (xs:NMTOKEN) -->
		</xs:complexType>
	</xs:element>
	<xs:element name="Schedule">
		<xs:complexType>
			<xs:attribute name="stopTime" default="0.0"/>
			<xs:attribute name="verbose" default="true">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="true"/>
						<xs:enumeration value="false"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="numberReplications" default="1"/>
			<xs:attribute name="printReplicationReports" default="true">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="true"/>
						<xs:enumeration value="false"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="printSummaryReport" default="true">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="true"/>
						<xs:enumeration value="false"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="saveReplicationData" default="true">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="true"/>
						<xs:enumeration value="false"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Adapter">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Coordinate" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="eventHeard" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="eventSent" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="from" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="to" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Log" type="xs:string"/>
	<xs:element name="Errors" type="xs:string"/>
	<xs:element name="PropertyChange">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Statistics" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="listenerName" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="property"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="SampleStatistics" substitutionGroup="Statistics">
		<xs:complexType>
			<xs:attribute name="name" type="xs:NMTOKEN"/>
			<xs:attribute name="mean" default="0.0"/>
			<xs:attribute name="variance" default="0.0"/>
			<xs:attribute name="standardDeviation" default="0.0"/>
			<xs:attribute name="count" default="0"/>
			<xs:attribute name="minObs" default="0.0"/>
			<xs:attribute name="maxObs" default="0.0"/>
			<xs:attribute name="samplingType" default="TALLY">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="TALLY"/>
						<xs:enumeration value="TIME_VARYING"/>
						<xs:enumeration value="LINEAR"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="IndexedSampleStatistics" substitutionGroup="Statistics">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SampleStatistics" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:NMTOKEN"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Results">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="Log"/>
				<xs:element ref="PropertyChange"/>
				<xs:element ref="Errors"/>
			</xs:choice>
			<xs:attribute name="sample" use="required"/>
			<xs:attribute name="designPoint" use="required"/>
			<xs:attribute name="index"/>
			<xs:attribute name="job"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="DesignPoint">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="TerminalParameter" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Script" minOccurs="0"/>
				<xs:element ref="Replication" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Results" minOccurs="0"/>
				<xs:element ref="Statistics" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="index"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Replication">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Statistics" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="index"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Script" type="xs:string"/>
	<xs:element name="Sample">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DesignPoint" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="index"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Experiment">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Script" minOccurs="0"/>
				<xs:element ref="Sample" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="jobID"/>
			<xs:attribute name="type" default="latin-hypercube">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="latin-hypercube"/>
						<xs:enumeration value="full-factorial"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="replicationsPerDesignPoint" default="1"/>
			<xs:attribute name="totalSamples" default="1"/>
			<xs:attribute name="jitter" default="true">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="true"/>
						<xs:enumeration value="false"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="timeout" default="0"/>
			<xs:attribute name="debug" default="false">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="true"/>
						<xs:enumeration value="false"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="EventGraph">
		<xs:complexType mixed="true">
			<xs:attribute name="fileName"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="PasswordFile">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="User" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" default="/tmp/passwd.xml"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="User">
		<xs:complexType>
			<xs:attribute name="name" type="xs:ID" use="required"/>
			<xs:attribute name="password" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== open-dis/viskit/MyViskitProjects/DefaultProject/Assemblies/examples/TestServerGenericAssembly.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimkitAssembly name="TestServerGenericAssembly" version="2.0" author='ahbuss' description="Provide a unit test for ServerGeneric event graph" package="examples" xsi:noNamespaceSchemaLocation="../../../../Schemas/assembly.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <SimEntity name="ServerGeneric" type="examples.ServerGeneric" description="">
        <TerminalParameter name="totalNumberServers" value="1" type="int"/>
        <FactoryParameter factory="simkit.random.RandomVariateFactory" type="simkit.random.RandomVariate">
            <TerminalParameter name="" value="Constant" type="java.lang.String"/>
            <TerminalParameter name="" value="1.1" type="double"/>
        </FactoryParameter>
        <Coordinate x="390.0" y="200.0"/>
    </SimEntity>
    <SimEntity name="ArrivalProcess" type="examples.ArrivalProcess" description="Provide arriving customers">
        <FactoryParameter factory="simkit.random.RandomVariateFactory" type="simkit.random.RandomVariate">
            <TerminalParameter name="" value="Exponential" type="java.lang.String"/>
            <TerminalParameter name="" value="1.2" type="double"/>
        </FactoryParameter>
        <Coordinate x="140.0" y="200.0"/>
    </SimEntity>
    <SimEntity name="EntityCreator" type="examples.EntityCreator" description="create entities">
        <Coordinate x="260.0" y="200.0"/>
    </SimEntity>
    <SimEventListenerConnection listener="EntityCreator" source="ArrivalProcess"/>
    <Adapter name="arrivalAdapter" eventHeard="EntityArrival" eventSent="Arrival" from="EntityCreator" to="ServerGeneric" description=""/>
    <Schedule stopTime="100." verbose="false" saveReplicationData="true"/>
    <Experiment replicationsPerDesignPoint="30" totalSamples="1" timeout="5000"/>
</SimkitAssembly>

=== open-dis/viskit/MyViskitProjects/DefaultProject/Assemblies/examples/InventoryModelAssembly.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimkitAssembly name="InventoryModelAssembly" version="1.0" package="examples" xsi:noNamespaceSchemaLocation="http://diana.nps.edu/Simkit/assembly.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <SimEntity name="arrivalProcess_0" type="examples.ArrivalProcess" description="">
        <FactoryParameter factory="simkit.random.RandomVariateFactory" type="simkit.random.RandomVariate">
            <TerminalParameter name="" value="Uniform" type="String"/>
            <TerminalParameter name="" value="0.9, 2.2" type="Object..."/>
        </FactoryParameter>
        <Coordinate x="100.0" y="200.0"/>
    </SimEntity>
    <SimEntity name="inventoryModel_1" type="examples.InventoryModel" description="">
        <FactoryParameter factory="simkit.random.RandomVariateFactory" type="simkit.random.RandomVariate">
            <TerminalParameter name="" value="DiscreteInteger" type="String"/>
            <TerminalParameter name="" value="new int[] {1, 2, 3, 4}, new double[] {40, 30, 20, 10}" type="Object..."/>
        </FactoryParameter>
        <FactoryParameter factory="simkit.random.RandomVariateFactory" type="simkit.random.RandomVariate">
            <TerminalParameter name="" value="Gamma" type="String"/>
            <TerminalParameter name="" value="1.7, 1.8" type="Object..."/>
        </FactoryParameter>
        <FactoryParameter factory="simkit.random.RandomVariateFactory" type="simkit.random.RandomVariate">
            <TerminalParameter name="" value="Constant" type="String"/>
            <TerminalParameter name="" value="1.8" type="java.lang.Object"/>
        </FactoryParameter>
        <TerminalParameter name="I0" value="15" type="int"/>
        <TerminalParameter name="bigS" value="10" type="int"/>
        <TerminalParameter name="littleS" value="5" type="int"/>
        <Coordinate x="410.0" y="200.0"/>
    </SimEntity>
    <SimEventListenerConnection listener="inventoryModel_1" source="arrivalProcess_0"/>
    <Schedule stopTime="100000.0" verbose="true"/>
</SimkitAssembly>

=== open-dis/viskit/MyViskitProjects/DefaultProject/Assemblies/examples/ServerWithRenegesAssembly.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimkitAssembly name="ServerWithRenegesAssembly" version="1.0" package="examples" description="TODO add description" xsi:noNamespaceSchemaLocation="http://diana.nps.edu/Simkit/assembly.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <SimEntity name="arrivalProcess" type="examples.ArrivalProcess">
        <FactoryParameter factory="simkit.random.RandomVariateFactory" type="simkit.random.RandomVariate">
            <TerminalParameter name="" value="Exponential" type="java.lang.String"/>
            <TerminalParameter name="" value="1.5" type="double"/>
        </FactoryParameter>
        <Coordinate x="40.0" y="140.0"/>
    </SimEntity>
    <SimEntity name="creator" type="examples.Creator">
        <Coordinate x="190.0" y="140.0"/>
    </SimEntity>
    <SimEntity name="serverWithReneges" type="examples.ServerWithReneges">
        <TerminalParameter name="numberServers" value="2" type="int"/>
        <FactoryParameter factory="simkit.random.RandomVariateFactory" type="simkit.random.RandomVariate">
            <TerminalParameter name="" value="Gamma" type="java.lang.String"/>
            <TerminalParameter name="" value="2.5" type="double"/>
            <TerminalParameter name="" value="1.2" type="double"/>
        </FactoryParameter>
        <FactoryParameter factory="simkit.random.RandomVariateFactory" type="simkit.random.RandomVariate">
            <TerminalParameter name="" value="Uniform" type="java.lang.String"/>
            <TerminalParameter name="" value="4" type="int"/>
            <TerminalParameter name="" value="6" type="int"/>
        </FactoryParameter>
        <Coordinate x="350.0" y="140.0"/>
    </SimEntity>
    <PropertyChangeListener name="numberInQueueStat" type="simkit.stat.CollectionSizeTimeVaryingStats" mode="replicationStat" meanStatistics="false" countStatistics="true">
        <TerminalParameter name="p[0] : " value="queue" type="java.lang.String"/>
        <Coordinate x="560.0" y="60.0"/>
    </PropertyChangeListener>
    <PropertyChangeListener name="numberAvailableServersStat" type="simkit.stat.SimpleStatsTally" mode="replicationStat" meanStatistics="false" countStatistics="true">
        <TerminalParameter name="p[0] : " value="numberAvailableServers" type="java.lang.String"/>
        <Coordinate x="350.0" y="290.0"/>
    </PropertyChangeListener>
    <PropertyChangeListener name="numberServedStat" type="simkit.stat.SimpleStatsTimeVarying" mode="replicationStat" meanStatistics="false" countStatistics="true">
        <TerminalParameter name="p[0] : " value="numberServed" type="java.lang.String"/>
        <Coordinate x="350.0" y="20.0"/>
    </PropertyChangeListener>
    <PropertyChangeListener name="numberRenegesStat" type="simkit.stat.SimpleStatsTimeVarying" mode="replicationStat" meanStatistics="false" countStatistics="true">
        <TerminalParameter name="p[0] : " value="numberReneges" type="java.lang.String"/>
        <Coordinate x="560.0" y="140.0"/>
    </PropertyChangeListener>
    <PropertyChangeListener name="numberArrivalsStat" type="simkit.stat.SimpleStatsTimeVarying" mode="replicationStat" meanStatistics="false" countStatistics="true">
        <TerminalParameter name="p[0] : " value="numberArrivals" type="java.lang.String"/>
        <Coordinate x="40.0" y="260.0"/>
    </PropertyChangeListener>
    <SimEventListenerConnection listener="creator" source="arrivalProcess"/>
    <PropertyChangeListenerConnection property="queue" listener="numberInQueueStat" source="serverWithReneges"/>
    <PropertyChangeListenerConnection property="numberAvailableServers" listener="numberAvailableServersStat" source="serverWithReneges"/>
    <PropertyChangeListenerConnection property="numberServed" listener="numberServedStat" source="serverWithReneges"/>
    <PropertyChangeListenerConnection property="numberReneges" listener="numberRenegesStat" source="serverWithReneges"/>
    <PropertyChangeListenerConnection property="numberArrivals" listener="numberArrivalsStat" source="arrivalProcess"/>
    <Adapter name="adptr_3" eventHeard="CustomerArrival" eventSent="Arrival" from="creator" to="serverWithReneges"/>
    <Output entity="creator"/>
    <Output entity="arrivalProcess"/>
    <Output entity="serverWithReneges"/>
    <Schedule stopTime="100.0" verbose="false"/>
    <Experiment replicationsPerDesignPoint="1" totalSamples="1" timeout="5000"/>
</SimkitAssembly>

=== open-dis/viskit/MyViskitProjects/DefaultProject/Assemblies/examples/ServerAssembly3.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimkitAssembly name="ServerAssembly3" version="2.0" package="examples" author="Arnie Buss" extend="viskit.assembly.ViskitAssembly" description="Show an example of multiple servers handling a markov chain." xsi:noNamespaceSchemaLocation="../../../../Schemas/assembly.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <SimEntity name="arrival" type="examples.ArrivalProcess" description="Customer arrival process, with each arriving after a probabilistic delay interval.">
        <FactoryParameter factory="simkit.random.RandomVariateFactory" type="simkit.random.RandomVariate">
            <TerminalParameter name="" value="Exponential" type="java.lang.String"/>
            <TerminalParameter name="" value="1.7" type="double"/>
        </FactoryParameter>
        <Coordinate x="90.0" y="90.0"/>
    </SimEntity>
    <SimEntity name="servers" type="examples.SimpleServer" description="Multiple-servers process handling arriving customers">
        <FactoryParameter factory="simkit.random.RandomVariateFactory" type="simkit.random.RandomVariate">
            <TerminalParameter name="" value="Gamma" type="java.lang.String"/>
            <TerminalParameter name="" value="2.1" type="double"/>
            <TerminalParameter name="" value="1.6" type="double"/>
        </FactoryParameter>
        <TerminalParameter name="totalNumberServers" value="2" type="int"/>
        <Coordinate x="280.0" y="90.0"/>
    </SimEntity>
    <PropertyChangeListener name="numberAvailableServersStatistic" type="simkit.stat.SimpleStatsTimeVarying" mode="replicationStat" meanStatistics="false" countStatistics="true" description="statistics regarding number of available servers">
        <TerminalParameter name="p[0] : " value="numberAvailableServers" type="java.lang.String"/>
        <Coordinate x="350.0" y="230.0"/>
    </PropertyChangeListener>
    <PropertyChangeListener name="numberInQueueStatistic" type="simkit.stat.SimpleStatsTimeVarying" mode="replicationStat" meanStatistics="false" countStatistics="true" description="statistic to measure queue status as it occurs">
        <TerminalParameter name="p[0] : " value="numberInQueue" type="java.lang.String"/>
        <Coordinate x="200.0" y="220.0"/>
    </PropertyChangeListener>
    <PropertyChangeListener name="simplePropertyDumper" type="simkit.util.SimplePropertyDumper" meanStatistics="false" countStatistics="true" description="record and dump simple property values">
        <Coordinate x="280.0" y="290.0"/>
    </PropertyChangeListener>
    <PropertyChangeListenerConnection property="numberInQueue" listener="numberInQueueStatistic" source="servers" description="listen for changes to number of customers in queue"/>
    <PropertyChangeListenerConnection property="numberAvailableServers" listener="numberAvailableServersStatistic" source="servers" description="property change connection listening to number of available servers"/>
    <PropertyChangeListenerConnection property="" listener="simplePropertyDumper" source="servers" description="monitor all simple property changes"/>
    <Adapter name="arrivalAdapter" eventHeard="Arrival" eventSent="Arrival" from="arrival" to="servers" description="adapter connection between arrival] and server processes"/>
    <Output entity="arrival"/>
    <Output entity="servers"/>
    <Schedule stopTime="1000" verbose="false" saveReplicationData="true"/>
    <Experiment replicationsPerDesignPoint="2" totalSamples="5" timeout="5000"/>
</SimkitAssembly>
