=== open-dis/viskit/Schemas/simkit.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- SVN ID: $Id$ -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="SimEntity">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="head" minOccurs="0"/>
				<xs:element ref="Comment" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Parameter" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="StateVariable" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Event" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Code" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="package" default="examples"/>
			<xs:attribute name="version" default="1.0"/>
			<xs:attribute name="author"/>
			<xs:attribute name="extend" default="SimEntityBase"/>
			<xs:attribute name="implement"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="head">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="meta" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="meta">
		<xs:complexType>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="content"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Comment" type="xs:string"/>
	<xs:element name="Parameter">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Comment" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:ID" use="required"/>
			<xs:attribute name="type" use="required"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="StateVariable">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Comment" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Code" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:ID" use="required"/>
			<xs:attribute name="type" use="required"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Event">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Comment" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Argument" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="LocalVariable" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="StateTransition" minOccurs="0" maxOccurs="unbounded"/>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="Schedule"/>
					<xs:element ref="Cancel"/>
				</xs:choice>
				<!-- Regardless of this sequence, code blocks will appear in the correct
             place in generated source code -->
				<xs:element ref="Code" minOccurs="0"/>
				<xs:element ref="Coordinate" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:ID" use="required"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Code" type="xs:string"/>
	<xs:element name="Argument">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Comment" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="type" use="required"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="LocalVariable">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Comment" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Code" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="type" use="required"/>
			<xs:attribute name="value"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Coordinate">
		<xs:complexType>
			<xs:attribute name="x" use="required"/> <!-- TODO  type="xs:float" -->
			<xs:attribute name="y" use="required"/> <!-- TODO  type="xs:float" -->
		</xs:complexType>
	</xs:element>
	<xs:element name="Operation">
		<xs:complexType>
			<xs:attribute name="method" use="required"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Assignment">
		<xs:complexType>
			<xs:attribute name="value" use="required"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="LocalVariableAssignment">
		<xs:complexType>
			<xs:attribute name="value"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="LocalVariableInvocation">
		<xs:complexType>
			<xs:attribute name="method"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<!-- bug fix 1183 -->
	<xs:element name="StateTransition">
		<xs:complexType>
			<xs:sequence>
				<xs:choice>
					<xs:element ref="Assignment"/>
					<xs:element ref="Operation"/>
				</xs:choice>
				<xs:element ref="LocalVariableAssignment" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="LocalVariableInvocation" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="Code" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="state" type="xs:IDREF" use="required"/>
			<xs:attribute name="index"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="EdgeParameter">
		<xs:complexType>
			<xs:attribute name="value" use="required"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Schedule">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Code" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Comment" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="EdgeParameter" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="delay" default="0.0"/>
			<xs:attribute name="event" type="xs:IDREF" use="required"/>
			<xs:attribute name="condition"/>
			<xs:attribute name="priority" default="DEFAULT">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="HIGHEST"/>
						<xs:enumeration value="HIGHER"/>
						<xs:enumeration value="HIGH"/>
						<xs:enumeration value="DEFAULT"/>
						<xs:enumeration value="LOW"/>
						<xs:enumeration value="LOWER"/>
						<xs:enumeration value="LOWEST"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Cancel">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Code" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Comment" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="EdgeParameter" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="event" type="xs:IDREF" use="required"/>
			<xs:attribute name="condition"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== open-dis/viskit/MyViskitProjects/DefaultProject/EventGraphs/examples/TransferLineComponent.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity name="TransferLineComponent" package="examples" version="0.0.2" extend="SimEntityBase" xsi:noNamespaceSchemaLocation="http://diana.nps.edu/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Comment>TODO: Fix me, I'm currently broken!! tdn 8/29/24</Comment>
    <Parameter name="totalNumberServers" type="int[]"/>
    <Parameter name="serviceTime" type="simkit.random.RandomVariate[]"/>
    <StateVariable name="numberAvailableServers" type="int[totalNumberServers.length]"/>
    <StateVariable name="numberInQueue" type="int[totalNumberServers.length]"/>
    <Event name="Run">
        <LocalVariable name="j" type="int" value="0">
            <Comment></Comment>
        </LocalVariable>
        <StateTransition state="numberAvailableServers" index="j>
            <Assignment value="totalNumberServers[j]"/>
        </StateTransition>
        <StateTransition state="numberInQueue" index="_idxvar_1">
            <Assignment value="0"/>
        </StateTransition>
        <Schedule delay="0.0" event="InitializeWorkcenter" priority="DEFAULT">
            <EdgeParameter value="0"/>
        </Schedule>
        <Coordinate x="0.0" y="0.0"/>
    </Event>
    <Event name="InitializeWorkcenter">
        <Argument name="i" type="int"/>
        <StateTransition state="numberInQueue" index="_idxvar_26">
            <Assignment value="0"/>
        </StateTransition>
        <StateTransition state="numberAvailableServers" index="_idxvar_27">
            <Assignment value="totalNumberServers[i]"/>
        </StateTransition>
        <Schedule event="InitializeWorkcenter" condition="i &lt; totalNumberServers.length - 1" priority="DEFAULT">
            <EdgeParameter value="i+1"/>
        </Schedule>
        <Coordinate x="120.0" y="0.0"/>
    </Event>
    <Event name="Arrival">
        <Argument name="i" type="int"/>
        <StateTransition state="numberInQueue" index="_idxvar_47">
            <Assignment value="numberInQueue[i] + 1"/>
        </StateTransition>
        <Schedule event="StartService" condition="getNumberAvailableServers(i) &gt; 0" priority="DEFAULT">
            <EdgeParameter value="i"/>
        </Schedule>
        <Coordinate x="0.0" y="180.0"/>
    </Event>
    <Event name="StartService">
        <Argument name="i" type="int"/>
        <StateTransition state="numberInQueue" index="_idxvar_48">
            <Assignment value="numberInQueue[i] + 1"/>
        </StateTransition>
        <StateTransition state="numberAvailableServers" index="_idxvar_49">
            <Assignment value="numberAvailableServers[i] - 1"/>
        </StateTransition>
        <Schedule delay="serviceTime[i].generate()" event="EndService" priority="DEFAULT">
            <EdgeParameter value="i"/>
        </Schedule>
        <Coordinate x="160.0" y="100.0"/>
    </Event>
    <Event name="EndService">
        <Argument name="i" type="int"/>
        <StateTransition state="numberAvailableServers" index="_idxvar_50">
            <Assignment value="numberAvailableServers[i]+1"/>
        </StateTransition>
        <Schedule event="StartService" condition="getNumberInQueue(i) &gt; 0" priority="DEFAULT"/>
        <Schedule event="Arrival" condition="i &lt; totalNumberServers.length - 1" priority="DEFAULT"/>
        <Coordinate x="330.0" y="200.0"/>
    </Event>
</SimEntity>

=== open-dis/viskit/MyViskitProjects/DefaultProject/EventGraphs/examples/SimpleServer.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity name="SimpleServer" package="examples" version="21 May 2016" extend="SimEntityBase" description="Model of a simple server" xsi:noNamespaceSchemaLocation="http://diana.nps.edu/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Parameter name="serviceTime" type="simkit.random.RandomVariate" description=""/>
    <Parameter name="totalNumberServers" type="int" description=""/>
    <StateVariable name="numberInQueue" type="int" description="number of arrivals waiting in queue"/>
    <StateVariable description="" name="numberAvailableServers" type="int"/>
    <Event name="Run" description="">
        <StateTransition state="numberInQueue">
            <Assignment value="0"/>
        </StateTransition>
        <StateTransition state="numberAvailableServers">
            <Assignment value="totalNumberServers"/>
        </StateTransition>
        <Coordinate x="20.0" y="30.0"/>
    </Event>
    <Event name="Arrival" description="">
        <StateTransition state="numberInQueue">
            <Assignment value="numberInQueue + 1"/>
        </StateTransition>
        <Schedule delay="0.0" event="StartService" condition="numberAvailableServers &gt; 0" priority="DEFAULT">
            <Comment></Comment>
            <EdgeParameter value="numberAvailableServers"/>
        </Schedule>
        <Coordinate x="20.0" y="120.0"/>
    </Event>
    <Event name="StartService" description="">
        <Comment></Comment>
        <Argument description="" name="arg_0" type="int"/>
        <StateTransition state="numberInQueue">
            <Assignment value="numberInQueue - 1"/>
        </StateTransition>
        <StateTransition state="numberAvailableServers">
            <Assignment value="numberAvailableServers - 1"/>
        </StateTransition>
        <Schedule delay="serviceTime.generate()" event="EndService" priority="DEFAULT"/>
        <Code>System.out.println("numberAvailableServers"+arg_0);</Code>
        <Coordinate x="170.0" y="140.0"/>
    </Event>
    <Event name="EndService" description="">
        <StateTransition state="numberAvailableServers">
            <Assignment value="numberAvailableServers + 1"/>
        </StateTransition>
        <Schedule delay="0.0" event="StartService" condition="numberInQueue &gt; 0" priority="HIGH"/>
        <Coordinate x="350.0" y="120.0"/>
    </Event>
</SimEntity>

=== open-dis/viskit/MyViskitProjects/DefaultProject/EventGraphs/examples/ArrayTester.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity name="ArrayTester" package="examples" version="1.0" author="Terry D. Norbraten" extend="SimEntityBase" description="Test Viskit's capability to create primitive type arrays" xsi:noNamespaceSchemaLocation="../../../../Schemas/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Parameter name="param_0" type="int[]" description="example parameter"/>
    <StateVariable name="state_0" type="int[param_0.length]" description="example state variable"/>
    <Event name="Run" description="The run event is started automatically by Simkit when execution starts.">
        <Schedule delay="0.0" event="Init" condition="true" priority="DEFAULT" description="always schedule event to initialize index at 0">
            <EdgeParameter value="0"/>
        </Schedule>
        <Code></Code>
        <Coordinate x="30.0" y="30.0"/>
    </Event>
    <Event name="Init" description="Initialize the event graph">
        <Argument name="i" type="int" description=""/>
        <StateTransition state="state_0" index="i">
            <Assignment value="param_0[i]"/>
        </StateTransition>
        <Schedule delay="0.0" event="Init" condition="i &lt; (param_0.length - 1)" priority="DEFAULT" description="Continue looping until array length reached">
            <EdgeParameter value="i + 1"/>
        </Schedule>
        <Code></Code>
        <Coordinate x="180.0" y="30.0"/>
    </Event>
</SimEntity>

=== open-dis/viskit/MyViskitProjects/DefaultProject/EventGraphs/examples/ServerGeneric.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity name="ServerGeneric" package="examples" version="2.0" author="ahbuss" description='Simple event graph example' extend="SimEntityBase" xsi:noNamespaceSchemaLocation="../../../../Schemas/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Parameter name="totalNumberServers" type="int" description="total number of servers available to serve customers"/>
    <Parameter name="serviceTimeGenerator" type="simkit.random.RandomVariate" description="random value for latest time duration to serve customer"/>
    <StateVariable name="numberAvailableServers" type="int" description="how many servers can serve customers"/>
    <StateVariable name="queue" type="java.util.LinkedList&lt;simkit.Entity&gt;" description="the queue holds customers who are waiting in line"/>
    <StateVariable name="delayInQueue" type="double" description="any fixed waiting time that all customers encounter"/>
    <StateVariable name="timeInSystem" type="double" description="how much time did the current customer need"/>
    <Event name="Run" description="">
        <StateTransition state="numberAvailableServers">
            <Assignment value="totalNumberServers"/>
        </StateTransition>
        <StateTransition state="queue">
            <Assignment value="new java.util.LinkedList&lt;simkit.Entity&gt;()"/>
        </StateTransition>
        <Code></Code>
        <Coordinate x="30.0" y="30.0"/>
    </Event>
    <Event name="Arrival">
        <Argument name="customer" type="simkit.Entity"/>
        <StateTransition state="queue">
            <Operation method="add(customer)"/>
        </StateTransition>
        <Schedule delay="0.0" event="StartService" condition="numberAvailableServers &gt; 0" priority="HIGH"/>
        <Code>customer.stampTime();</Code>
        <Coordinate x="30.0" y="170.0"/>
    </Event>
    <Event name="StartService">
        <StateTransition state="numberAvailableServers">
            <Assignment value="numberAvailableServers - 1"/>
        </StateTransition>
        <StateTransition state="queue">
            <Operation method="removeFirst()"/>
        </StateTransition>
        <StateTransition state="delayInQueue">
            <Assignment value="customer.getElapsedTime()"/>
        </StateTransition>
        <Schedule delay="serviceTimeGenerator.generate()" event="EndService" condition="true" priority="DEFAULT">
            <EdgeParameter value="customer"/>
        </Schedule>
        <Code>Entity customer = queue.getFirst();</Code>
        <Coordinate x="170.0" y="160.0"/>
    </Event>
    <Event name="EndService">
        <Argument name="customer" type="simkit.Entity"/>
        <StateTransition state="numberAvailableServers">
            <Assignment value="numberAvailableServers + 1"/>
        </StateTransition>
        <StateTransition state="timeInSystem">
            <Assignment value="customer.getElapsedTime()"/>
        </StateTransition>
        <Schedule delay="0.0" event="StartService" condition="queue.size() &gt; 0" priority="HIGH">
        </Schedule>
        <Code></Code>
        <Coordinate x="290.0" y="160.0"/>
    </Event>
</SimEntity>
