=== open-dis/viskit/Schemas/simkit.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- SVN ID: $Id$ -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="SimEntity">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="head" minOccurs="0"/>
				<xs:element ref="Comment" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Parameter" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="StateVariable" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Event" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Code" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="package" default="examples"/>
			<xs:attribute name="version" default="1.0"/>
			<xs:attribute name="author"/>
			<xs:attribute name="extend" default="SimEntityBase"/>
			<xs:attribute name="implement"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="head">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="meta" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="meta">
		<xs:complexType>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="content"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Comment" type="xs:string"/>
	<xs:element name="Parameter">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Comment" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:ID" use="required"/>
			<xs:attribute name="type" use="required"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="StateVariable">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Comment" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Code" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:ID" use="required"/>
			<xs:attribute name="type" use="required"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Event">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Comment" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Argument" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="LocalVariable" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="StateTransition" minOccurs="0" maxOccurs="unbounded"/>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="Schedule"/>
					<xs:element ref="Cancel"/>
				</xs:choice>
				<!-- Regardless of this sequence, code blocks will appear in the correct
             place in generated source code -->
				<xs:element ref="Code" minOccurs="0"/>
				<xs:element ref="Coordinate" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:ID" use="required"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Code" type="xs:string"/>
	<xs:element name="Argument">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Comment" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="type" use="required"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="LocalVariable">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Comment" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Code" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="type" use="required"/>
			<xs:attribute name="value"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Coordinate">
		<xs:complexType>
			<xs:attribute name="x" use="required"/> <!-- TODO  type="xs:float" -->
			<xs:attribute name="y" use="required"/> <!-- TODO  type="xs:float" -->
		</xs:complexType>
	</xs:element>
	<xs:element name="Operation">
		<xs:complexType>
			<xs:attribute name="method" use="required"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Assignment">
		<xs:complexType>
			<xs:attribute name="value" use="required"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="LocalVariableAssignment">
		<xs:complexType>
			<xs:attribute name="value"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="LocalVariableInvocation">
		<xs:complexType>
			<xs:attribute name="method"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<!-- bug fix 1183 -->
	<xs:element name="StateTransition">
		<xs:complexType>
			<xs:sequence>
				<xs:choice>
					<xs:element ref="Assignment"/>
					<xs:element ref="Operation"/>
				</xs:choice>
				<xs:element ref="LocalVariableAssignment" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="LocalVariableInvocation" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="Code" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="state" type="xs:IDREF" use="required"/>
			<xs:attribute name="index"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="EdgeParameter">
		<xs:complexType>
			<xs:attribute name="value" use="required"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Schedule">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Code" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Comment" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="EdgeParameter" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="delay" default="0.0"/>
			<xs:attribute name="event" type="xs:IDREF" use="required"/>
			<xs:attribute name="condition"/>
			<xs:attribute name="priority" default="DEFAULT">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="HIGHEST"/>
						<xs:enumeration value="HIGHER"/>
						<xs:enumeration value="HIGH"/>
						<xs:enumeration value="DEFAULT"/>
						<xs:enumeration value="LOW"/>
						<xs:enumeration value="LOWER"/>
						<xs:enumeration value="LOWEST"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Cancel">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Code" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Comment" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="EdgeParameter" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="event" type="xs:IDREF" use="required"/>
			<xs:attribute name="condition"/>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== open-dis/viskit/MyViskitProjects/DefaultProject/EventGraphs/examples/ServerWithReneges.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity name="ServerWithReneges" package="examples" version="2.0" extend="SimEntityBase" description="Event graph for server handling customers and reneges" xsi:noNamespaceSchemaLocation="../../../../Schemas/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Parameter name="numberServers" type="int" description="total number of servers"/>
    <Parameter name="serviceTime" type="simkit.random.RandomVariate" description="probablilistic time duration to service a customer"/>
    <Parameter name="renegeTime" type="simkit.random.RandomVariate" description="likely wait time before a customer decides to reneqe and get out of the service line"/>
    <StateVariable name="numberAvailableServers" type="int" description="current number of available servers"/>
    <StateVariable name="queue" type="java.util.LinkedList&lt;Integer&gt;" description="ordered list of waiting customers, First In FIrst Out (FIFO)"/>
    <StateVariable name="numberServed" type="int" description="how many customers have been successfully served"/>
    <StateVariable name="numberReneges" type="int" description="count number of customer reneges"/>
    <Event name="Run" description="This event is automatically scheduled to occur when the simulation begins to run, enabling author to schedule commencement of first simulation activity.">
        <StateTransition state="numberAvailableServers">
            <Assignment value="getNumberServers()"/>
        </StateTransition>
        <StateTransition state="queue">
            <Operation method="clear()"/>
        </StateTransition>
        <StateTransition state="numberServed">
            <Assignment value="0"/>
        </StateTransition>
        <StateTransition state="numberReneges">
            <Assignment value="0"/>
        </StateTransition>
        <Code></Code>
        <Coordinate x="70.0" y="70.0"/>
    </Event>
    <Event name="Arrival" description="customer has arrived">
        <Argument name="customer" type="java.lang.Integer" description=""/>
        <StateTransition state="queue">
            <Operation method="add(customer)"/>
        </StateTransition>
        <Schedule delay="renegeTime.generate()" event="Renege" priority="DEFAULT" description="designate a probabilistic subset of customers who decide to renege">
            <EdgeParameter value="customer"/>
        </Schedule>
        <Schedule delay="0.0" event="StartService" condition="getNumberAvailableServers() &gt; 0" priority="DEFAULT" description="activate the next server to handle this customer arrival"/>
        <Code></Code>
        <Coordinate x="70.0" y="170.0"/>
    </Event>
    <Event name="StartService" description="commence service for current customer, schedule completion time">
        <LocalVariable name="customer" type="java.lang.Integer" value="queue.getFirst()" description="ID number for current customer"/>
        <StateTransition state="queue">
            <Operation method="removeFirst()"/>
        </StateTransition>
        <StateTransition state="numberAvailableServers">
            <Assignment value="numberAvailableServers - 1"/>
        </StateTransition>
        <Cancel event="Renege" description="cancel service for this customer">
            <EdgeParameter value="customer"/>
        </Cancel>
        <Schedule delay="serviceTime.generate()" event="EndService" priority="DEFAULT" description="schedule completion of this customer following a probabilistic serviceTime interval">
            <EdgeParameter value="customer"/>
        </Schedule>
        <Code></Code>
        <Coordinate x="210.0" y="160.0"/>
    </Event>
    <Event name="EndService" description="customer service activity complete">
        <Argument name="customer1" type="java.lang.Integer" description=""/>
        <StateTransition state="numberAvailableServers">
            <Assignment value="numberAvailableServers+1"/>
        </StateTransition>
        <StateTransition state="numberServed">
            <Assignment value="numberServed+1"/>
        </StateTransition>
        <Schedule delay="0.0" event="StartService" condition="queue.size() &gt; 0" priority="HIGH" description="once prior customer has been served, announce availability of this server for next customer"/>
        <Code></Code>
        <Coordinate x="340.0" y="160.0"/>
    </Event>
    <Event name="Renege" description="customer reneges out of line, no longer requesting service">
        <Argument name="customer2" type="java.lang.Integer" description=""/>
        <StateTransition state="queue">
            <Operation method="remove(customer2)"/>
        </StateTransition>
        <StateTransition state="numberReneges">
            <Assignment value="numberReneges+1"/>
        </StateTransition>
        <Code></Code>
        <Coordinate x="140.0" y="280.0"/>
    </Event>
</SimEntity>

=== open-dis/viskit/MyViskitProjects/DefaultProject/EventGraphs/examples/InventoryModel.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity name="InventoryModel" package="examples" version="1.0" author="terry" extend="SimEntityBase" xsi:noNamespaceSchemaLocation="http://diana.nps.edu/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Comment>Implementation of an Event Graph for an Inventory Model employing an (s, S) ordering policy depicted on page 4-6 of the Discrete Event Simulation (DES) Modeling guide by Arnie Buss.</Comment>
    <Parameter name="D" type="simkit.random.RandomVariate">
        <Comment>Number of Parts demanded by a customer</Comment>
    </Parameter>
    <Parameter name="tL" type="simkit.random.RandomVariate">
        <Comment>Lead time for orders received by the company</Comment>
    </Parameter>
    <Parameter name="tR" type="simkit.random.RandomVariate">
        <Comment>Deterministic time between company reviews</Comment>
    </Parameter>
    <Parameter name="I0" type="int">
        <Comment>Initial inventory of Parts</Comment>
    </Parameter>
    <Parameter name="bigS" type="int">
        <Comment>Order up to amount (S)</Comment>
    </Parameter>
    <Parameter name="littleS" type="int">
        <Comment>Order trigger amount (s)</Comment>
    </Parameter>
    <StateVariable name="I" type="int">
        <Comment>Amount of Parts on hand</Comment>
    </StateVariable>
    <StateVariable name="B" type="int">
        <Comment>Amount of Parts on backorder</Comment>
    </StateVariable>
    <StateVariable name="T" type="int">
        <Comment>Total amount of Parts on order</Comment>
    </StateVariable>
    <StateVariable name="N" type="int">
        <Comment>Number of Parts ordered</Comment>
    </StateVariable>
    <StateVariable name="NO" type="int">
        <Comment>Number of orders placed</Comment>
    </StateVariable>
    <StateVariable name="immediatelyServedCustomers" type="int">
        <Comment>Customers immediately served</Comment>
    </StateVariable>
    <Event name="Run" description="This event is fired first to facilitate initialization of all simulation state variables">
        <Comment></Comment>
        <StateTransition state="I">
            <Assignment value="I0"/>
        </StateTransition>
        <StateTransition state="B">
            <Assignment value="0"/>
        </StateTransition>
        <StateTransition state="T">
            <Assignment value="0"/>
        </StateTransition>
        <StateTransition state="N">
            <Assignment value="0"/>
        </StateTransition>
        <StateTransition state="NO">
            <Assignment value="0"/>
        </StateTransition>
        <StateTransition state="immediatelyServedCustomers">
            <Assignment value="0"/>
        </StateTransition>
        <Schedule delay="tR.generate()" event="Review" priority="DEFAULT">
            <Comment></Comment>
        </Schedule>
        <Code></Code>
        <Coordinate x="40.0" y="200.0"/>
    </Event>
    <Event name="Arrival">
        <Comment>Feeder event for schedulling the Demand event via Arrivals from the Arrival Process</Comment>
        <Schedule delay="0.0" event="Demand" priority="DEFAULT">
            <Comment>Passing along tA</Comment>
        </Schedule>
        <Code></Code>
        <Coordinate x="40.0" y="100.0"/>
    </Event>
    <Event name="Demand">
        <Comment></Comment>
        <LocalVariable name="demand" type="int" value="((DiscreteRandomVariate) D).generateInt()">
            <Comment></Comment>
        </LocalVariable>
        <LocalVariable name="net" type="int" value="I-B-demand">
            <Comment></Comment>
        </LocalVariable>
        <StateTransition state="I">
            <Assignment value="Math.max(0, net)"/>
        </StateTransition>
        <StateTransition state="B">
            <Assignment value="Math.max(0, -net)"/>
        </StateTransition>
        <Code>firePropertyChange("demand", demand);

if (net &gt;= 0) {
   int oldImmediatelyServedCustomers = immediatelyServedCustomers;
   immediatelyServedCustomers += 1;
   firePropertyChange("immediatelyServedCustomers", oldImmediatelyServedCustomers, immediatelyServedCustomers);
}</Code>
        <Coordinate x="150.0" y="100.0"/>
    </Event>
    <Event name="Review">
        <Comment></Comment>
        <Schedule delay="0.0" event="PlaceOrder" condition="(I-B+T) &lt; littleS" priority="DEFAULT">
            <Comment></Comment>
            <EdgeParameter value="bigS - I + B - T"/>
        </Schedule>
        <Schedule delay="tR.generate()" event="Review" priority="DEFAULT">
            <Comment></Comment>
        </Schedule>
        <Code></Code>
        <Coordinate x="140.0" y="290.0"/>
    </Event>
    <Event name="PlaceOrder">
        <Comment></Comment>
        <Argument name="A" type="int"/>
        <StateTransition state="T">
            <Assignment value="T+A"/>
        </StateTransition>
        <StateTransition state="N">
            <Assignment value="N+A"/>
        </StateTransition>
        <StateTransition state="NO">
            <Assignment value="NO + 1"/>
        </StateTransition>
        <Schedule delay="tL.generate()" event="OrderArrives" priority="DEFAULT">
            <Comment></Comment>
            <EdgeParameter value="A"/>
        </Schedule>
        <Code></Code>
        <Coordinate x="280.0" y="300.0"/>
    </Event>
    <Event name="OrderArrives">
        <Comment></Comment>
        <Argument name="A" type="int"/>
        <LocalVariable name="net" type="int" value="I - B + A">
            <Comment></Comment>
        </LocalVariable>
        <StateTransition state="T">
            <Assignment value="T - A"/>
        </StateTransition>
        <StateTransition state="I">
            <Assignment value="Math.max(0, net)"/>
        </StateTransition>
        <StateTransition state="B">
            <Assignment value="Math.max(0, -net)"/>
        </StateTransition>
        <Code></Code>
        <Coordinate x="400.0" y="300.0"/>
    </Event>
</SimEntity>

=== open-dis/viskit/MyViskitProjects/DefaultProject/EventGraphs/examples/SimpleMachineFailure.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity name="SimpleMachineFailure" version="0.1" package="examples" description="" xsi:noNamespaceSchemaLocation="http://eos.nps.edu/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Parameter description="" type="int" name="totalNumberMachines"/>
    <Parameter description="" type="int" name="totalNumberRepairPeople"/>
    <Parameter description="" type="simkit.random.RandomVariate" name="timeToFailure"/>
    <Parameter description="" type="simkit.random.RandomVariate" name="repairTime"/>
    <StateVariable description="" name="numberFailedMachines" type="int" />
    <StateVariable description="" name="numberAvailableRepairPeople" type="int" />
    <Event name="Run" description="">
        <StateTransition state="numberFailedMachines">
            <Assignment value="totalNumberMachines"/>
        </StateTransition>
        <StateTransition state="numberAvailableRepairPeople">
            <Assignment value="totalNumberRepairPeople"/>
        </StateTransition>
        <Schedule delay="0.0" event="StartMachine"/>
        <Coordinate y="0" x="0"/>
    </Event>
    <Event name="StartMachine" description="">
        <StateTransition state="numberFailedMachines">
            <Assignment value="numberFailedMachines - 1"/>
        </StateTransition>
        <Schedule delay="timeToFailure.generate()" event="Failure"/>
        <Schedule condition="numberFailedMachines &gt; 0" delay="0.0" event="StartMachine"/>
        <Coordinate y="0" x="80"/>
    </Event>
    <Event name="Failure" description="">
        <StateTransition state="numberFailedMachines">
            <Assignment value="numberFailedMachines + 1"/>
        </StateTransition>
        <Schedule condition="numberAvailableRepairPeople &gt; 0" delay="0.0" event="StartRepair"/>
        <Coordinate y="160" x="80"/>
    </Event>
    <Event name="StartRepair" description="">
        <StateTransition state="numberAvailableRepairPeople">
            <Assignment value="numberAvailableRepairPeople - 1"/>
        </StateTransition>
        <Schedule delay="repairTime.generate()" event="EndRepair"/>
        <Coordinate y="160" x="280"/>
    </Event>
    <Event name="EndRepair" description="">
        <StateTransition state="numberAvailableRepairPeople">
            <Assignment value="numberAvailableRepairPeople + 1"/>
        </StateTransition>
        <StateTransition state="numberFailedMachines">
            <Assignment value="numberFailedMachines - 1"/>
        </StateTransition>
        <Schedule condition="numberFailedMachines &gt;= totalNumberRepairPeople" priority="HIGH" delay="0.0" event="StartRepair"/>
        <Schedule delay="timeToFailure.generate()" event="Failure"/>
        <Coordinate y="10" x="280"/>
    </Event>
</SimEntity>

=== open-dis/viskit/test/ArrayTester.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity extend="SimEntityBase" name="ArrayTester" package="test" version="$Id:$" description="empty" xsi:noNamespaceSchemaLocation="http://eos.nps.edu/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <StateVariable name="sinus" type="double[180]" description="empty">
        <Comment/>
    </StateVariable>
    <Event name="Run" description="empty">
        <Comment/>
        <LocalVariable name="_idxvar_0" type="int" value="0">
            <Comment>used internally</Comment>
        </LocalVariable>
        <StateTransition index="_idxvar_0" state="sinus">
            <Assignment value="Math.sin(2.0*Math.PI*((double)_idxvar_0)/((double)180))"/>
        </StateTransition>
        <Schedule condition="true" delay="0.0" event="DumpArrayElement" priority="0">
            <Comment/>
            <EdgeParameter value="0"/>
        </Schedule>
        <Coordinate x="30" y="30"/>
    </Event>
    <Event name="DumpArrayElement" description="empty">
        <Comment/>
        <Argument name="i" type="int" description="empty"/>
        <LocalVariable name="code" type="boolean" value="true; System.out.println(getSinus(i))">
            <Comment/>
        </LocalVariable>
        <Schedule condition="i&lt;180" delay="0.0" event="DumpArrayElement" priority="0">
            <Comment/>
            <EdgeParameter value="i++"/>
        </Schedule>
        <Code>

System.out.println("Element "+i + " dumped. ");
if ( true ) {
	System.out.println("");
}

	</Code>
        <Coordinate x="200" y="110"/>
    </Event>
</SimEntity>

=== open-dis/viskit/MyViskitProjects/DefaultProject/EventGraphs/examples/ArrivalProcess.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity name="ArrivalProcess" package="examples" version="21 May 2016" extend="SimEntityBase" description="Model of a simple recurring Arrival process" xsi:noNamespaceSchemaLocation="http://eos.nps.edu/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Parameter name="interarrivalTime" type="simkit.random.RandomVariate" description="todo"/>
    <StateVariable name="numberArrivals" type="int" description=""/>
    <Event name="Run" description="">
        <StateTransition state="numberArrivals">
            <Assignment value="0"/>
        </StateTransition>
        <Schedule delay="interarrivalTime.generate()" event="Arrival" priority="DEFAULT"/>
        <Coordinate x="50.0" y="80.0"/>
    </Event>
    <Event name="Arrival" description="">
        <StateTransition state="numberArrivals">
            <Assignment value="numberArrivals + 1"/>
        </StateTransition>
        <Schedule delay="interarrivalTime.generate()" event="Arrival" priority="DEFAULT"/>
        <Coordinate x="260.0" y="80.0"/>
    </Event>
</SimEntity>

=== open-dis/viskit/MyViskitProjects/DefaultProject/EventGraphs/examples/Creator.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity name="Creator" package="examples" version="2.0" author="Arnie Buss" extend="SimEntityBase" description="Creator process creates customer entites" xsi:noNamespaceSchemaLocation="../../../../Schemas/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <StateVariable name="nextID" type="int" description="identifying number of next customer"/>
    <Event name="Arrival" description="Each customer is sequentially numbered">
        <StateTransition state="nextID">
            <Assignment value="nextID+1"/>
        </StateTransition>
        <Schedule delay="0.0" event="CustomerArrival" priority="DEFAULT" description="Each arriving customer produces an event">
            <EdgeParameter value="nextID"/>
        </Schedule>
        <Code></Code>
        <Coordinate x="30.0" y="120.0"/>
    </Event>
    <Event name="CustomerArrival">
        <Argument name="customer" type="Integer" description=""/>
        <Code></Code>
        <Coordinate x="190.0" y="120.0"/>
    </Event>
    <Event name="Run" description="This event is automatically scheduled to occur when the simulation begins to run, enabling an author to schedule commencement of the first activity">
        <StateTransition state="nextID">
            <Assignment value="0"/>
        </StateTransition>
        <Code></Code>
        <Coordinate x="30.0" y="10.0"/>
    </Event>
</SimEntity>

=== open-dis/viskit/MyViskitProjects/DefaultProject/EventGraphs/examples/SimpleInventory.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SimEntity name="SimpleInventory" version="0.1" package="examples" description="" xsi:noNamespaceSchemaLocation="http://eos.nps.edu/Simkit/simkit.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Parameter description="" type="simkit.random.RandomVariate" name="timeBetweenDemands"/>
    <Parameter description="" type="simkit.random.RandomVariate" name="demand"/>
    <Parameter description="" type="simkit.random.RandomVariate" name="leadTime"/>
    <Parameter description="" type="double" name="timeBetweenReviews"/>
    <Parameter description="" type="double" name="initialInventory"/>
    <Parameter description="" type="double" name="triggerPoint"/>
    <Parameter description="" type="double" name="orderUpTo"/>
    <StateVariable description="" name="inventoryPosition" type="double" />
    <StateVariable description="" name="amountOnOrder" type="double" />
    <Event name="Run" description="">
        <StateTransition state="inventoryPosition">
            <Assignment value="initialInventory"/>
        </StateTransition>
        <StateTransition state="amountOnOrder">
            <Assignment value="0"/>
        </StateTransition>
        <Schedule delay="timeBetweenReviews" event="Review"/>
        <Schedule delay="timeBetweenDemands.generate()" event="Demand"/>
        <Coordinate y="20" x="10"/>
    </Event>
    <Event name="Demand" description="">
        <StateTransition state="inventoryPosition">
            <Assignment value="inventoryPosition - demand.generate()"/>
        </StateTransition>
        <Schedule delay="timeBetweenDemands.generate()" event="Demand"/>
        <Coordinate y="20" x="160"/>
    </Event>
    <Event name="Review" description="">
        <Schedule condition="inventoryPosition + amountOnOrder &lt; triggerPoint" delay="0.0" event="PlaceOrder">
            <EdgeParameter value="(orderUpTo - inventoryPosition - amountOnOrder)"/>
        </Schedule>
        <Schedule delay="timeBetweenReviews" event="Review"/>
        <Coordinate y="140" x="80"/>
    </Event>
    <Event name="PlaceOrder" description="">
        <Argument description="" name="newOrderAmount" type="double"/>
        <StateTransition state="amountOnOrder">
            <Assignment value="amountOnOrder + newOrderAmount"/>
        </StateTransition>
        <Schedule delay="leadTime.generate()" event="ReceiveOrder">
            <EdgeParameter value="newOrderAmount"/>
        </Schedule>
        <Coordinate y="150" x="190"/>
    </Event>
    <Event name="ReceiveOrder" description="">
        <Argument description="" name="receivedOrderAmount" type="double"/>
        <StateTransition state="amountOnOrder">
            <Assignment value="amountOnOrder - receivedOrderAmount"/>
        </StateTransition>
        <StateTransition state="inventoryPosition">
            <Assignment value="inventoryPosition + receivedOrderAmount"/>
        </StateTransition>
        <Coordinate y="150" x="310"/>
    </Event>
</SimEntity>
